s= "hello world"
print(s.capitalize())
print(s.find("world"))
print(s.replace("world","nancy"))
print(s.count("o"))
print(s.isalpha())
print(s.isdigit())
print(s.isalnum())
print(s.isspace())
print(s.rfind("o"))
print(s.index("l"))
print(s.split())
print(s.splitlines())
print(s.join(""))